### ISSUE TITLE
Organizations vs. OrganizationalUnits #2

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/harvesters#14]
Please keep in mind that the actual class is elod:Organization**al**Unit, which should be reflected in the URI (e.g. http://linkedeconomy.org/resource/OrganizationalUnit/80428).

**Comment by mogaio** [comment]
We updated our mapping of the authorities resources to fit the requirements of the elod:contractingAuthority property since it's range is gr:BusinessEntity so there is no need to use elod:OrganizationalUnit any more, all our URIs updated according to these changes and using the Organization URI "http://linkedeconomy.org/resource/Organization/"

**Comment by Polymathronic** [comment]
I don't see a _mapping_ for the property in the spreadsheet. What is this based on?

**Comment by mogaio** [comment]
elod:contractingAuthority is mapped to a gr:BusinessEntity resource (accoriding to the elod ontology) that contains the contract_authority_official_name and the contracting authority country (according to https://github.com/YourDataStories/harvesters/issues/20)

**Comment by Polymathronic** [comment]
I guess you mean `pc:contractingAuthority`. There is no way one could infer what you are saying based on what is in the spreadsheet. The reason for this is the fact that you didn't follow the proposed data analysis approach, but decided to go with your own template.

Anyway, we have already drifted off topic; I guess @vafopoulos can decide whether the spreadsheet is in an acceptable state, and open a separate GitHub issue in the ontology repository if not.
